version: '3.9'
networks:
  web:

services: 
  mdb:
    build: ./docker/mongo
    image: nextuponstream/wrb_mongo
    container_name: ${CONTAINER_NAME_MONGO}
    env_file:  
      - .env
    ports: 
      - 8444:27017
    networks: 
      - web
  ngdb:
    build: ./docker/neo4j
    image: nextuponstream/wrb_neo4j
    container_name: wrb_ngdb
    env_file:  
      - .env
    ports:
      - 7474:7474 
      - 7687:7687
    networks: 
      - web

  bot:
    build: ./docker/go
    image: nextuponstream/wrb_bot
    container_name: wrb_go
    env_file:  
      - .env
    ports: 
      - 8443:3000
    networks: 
      - web
